import type { Metadata } from 'next';

import { Geist, Geist_Mono as GeistMono } from 'next/font/google';
import { notFound } from 'next/navigation';

import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

import { routing } from '@/features/i18n/infrastructure/config/routing';
import { LocaleSwitcher } from '@/features/i18n/presentation/components/locale-switcher';
import { ThemeProvider } from '@/features/theme/presentation/components/theme-provider';
import { ThemeToggle } from '@/features/theme/presentation/components/theme-toggle';

import '../globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = GeistMono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const LocaleLayout: React.FC<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}> = async ({ children, params }) => {
  const { locale } = await params;

  if (!routing.locales.includes(locale as 'en' | 'th')) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider>
            <ThemeToggle />
            <LocaleSwitcher />
            {children}
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default LocaleLayout;
